// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class GcsLightsAvro : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"GcsLightsAvro\",\"namespace\":\"Avro\",\"fields\":[{\"name\":\"IsN" +
				"avLightsOn\",\"type\":\"boolean\"},{\"name\":\"IsStrobLightsOn\",\"type\":\"boolean\"}]}");
		private bool _IsNavLightsOn;
		private bool _IsStrobLightsOn;
		public virtual Schema Schema
		{
			get
			{
				return GcsLightsAvro._SCHEMA;
			}
		}
		public bool IsNavLightsOn
		{
			get
			{
				return this._IsNavLightsOn;
			}
			set
			{
				this._IsNavLightsOn = value;
			}
		}
		public bool IsStrobLightsOn
		{
			get
			{
				return this._IsStrobLightsOn;
			}
			set
			{
				this._IsStrobLightsOn = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.IsNavLightsOn;
			case 1: return this.IsStrobLightsOn;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.IsNavLightsOn = (System.Boolean)fieldValue; break;
			case 1: this.IsStrobLightsOn = (System.Boolean)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
